apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastfood-backend
  namespace: fastfood
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fastfood-backend
  template:
    metadata:
      labels:
        app: fastfood-backend
    spec:
      containers:
        - name: fastfood-backend
          image: fastfood-backend:v2
          imagePullPolicy: Never
          ports:
            - containerPort: 5000
          env:
            - name: MONGO_URL
              value: mongodb://mongodb:27017/fastfood

---
apiVersion: v1
kind: Service
metadata:
  name: fastfood-backend
  namespace: fastfood
spec:
  selector:
    app: fastfood-backend
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: ClusterIP
